# Generated by Django 5.2.1 on 2025-05-24 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('prezime', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('korisnicko_ime', models.CharField(max_length=100, unique=True)),
                ('lozinka_hash', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pacijent',
            fields=[
                ('korisnik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Pacijenti.korisnik')),
                ('povijest_bolesti', models.TextField(blank=True)),
                ('simptomi_bolesti', models.TextField(blank=True)),
                ('primljena_cijepiva', models.TextField(blank=True)),
            ],
        ),
    ]
