# Generated by Django 5.2.1 on 2025-05-25 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacijenti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doktor',
            fields=[
                ('korisnik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Pacijenti.korisnik')),
                ('specijalizacija', models.CharField(max_length=100)),
                ('razina_specijalizacije', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MedicinskaSestra',
            fields=[
                ('korisnik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Pacijenti.korisnik')),
                ('radno_iskustvo', models.CharField(max_length=100)),
                ('specializirane_tehnike', models.TextField()),
                ('doktor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sestre', to='Pacijenti.doktor')),
            ],
        ),
    ]
