# Generated by Django 5.2.1 on 2025-05-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacijenti', '0002_doktor_medicinskasestra'),
    ]

    operations = [
        migrations.AddField(
            model_name='korisnik',
            name='uloga',
            field=models.CharField(choices=[('pacijent', 'Pacijent'), ('doktor', 'Doktor'), ('sestra', 'Medicinska sestra')], default='pacijent', max_length=20),
        ),
    ]
