# Generated by Django 5.1.7 on 2025-06-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacijenti', '0004_infirmary'),
    ]

    operations = [
        migrations.AddField(
            model_name='infirmary',
            name='Infirmary_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
