# Generated by Django 5.1.7 on 2025-08-19 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacijenti', '0005_infirmary_infirmary_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('note', models.TextField(blank=True, default='')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Zakazano'), ('confirmed', 'Potvrđeno'), ('cancelled', 'Otkazano'), ('completed', 'Završeno'), ('no_show', 'Nije došao')], default='scheduled', max_length=16)),
                ('priority', models.CharField(default='normal', max_length=16)),
                ('recurrence_rule', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doktor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='Pacijenti.doktor')),
                ('infirmary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='Pacijenti.infirmary')),
                ('pacijent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='Pacijenti.pacijent')),
                ('sestra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='Pacijenti.medicinskasestra')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('pacijent', 'Pacijent'), ('doktor', 'Doktor'), ('sestra', 'Medicinska sestra')], max_length=16)),
                ('response_status', models.CharField(choices=[('invited', 'Pozvan'), ('accepted', 'Prihvatio'), ('declined', 'Odbio'), ('tentative', 'Možda'), ('attended', 'Prisustvovao'), ('no_show', 'Nije došao')], default='invited', max_length=16)),
                ('reminder_offset_min', models.IntegerField(blank=True, null=True)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='Pacijenti.appointment')),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_participations', to='Pacijenti.korisnik')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doktor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='Pacijenti.doktor')),
                ('pacijent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='Pacijenti.pacijent')),
                ('sestra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='Pacijenti.medicinskasestra')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, default='')),
                ('type', models.CharField(default='text', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='Pacijenti.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('pacijent', 'Pacijent'), ('doktor', 'Doktor'), ('sestra', 'Medicinska sestra')], max_length=16)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='Pacijenti.conversation')),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_participations', to='Pacijenti.korisnik')),
            ],
        ),
        migrations.CreateModel(
            name='MessageStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='Pacijenti.message')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_statuses', to='Pacijenti.participant')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_messages', to='Pacijenti.participant'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['start_time'], name='Pacijenti_a_start_t_26d92e_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['end_time'], name='Pacijenti_a_end_tim_06ac2e_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status'], name='Pacijenti_a_status_2a3be4_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['pacijent'], name='Pacijenti_a_pacijen_bb2103_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doktor'], name='Pacijenti_a_doktor__6c91e2_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['sestra'], name='Pacijenti_a_sestra__d8c6b0_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentattendee',
            index=models.Index(fields=['appointment', 'korisnik'], name='Pacijenti_a_appoint_0610d1_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentattendee',
            index=models.Index(fields=['role'], name='Pacijenti_a_role_744aad_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentattendee',
            index=models.Index(fields=['response_status'], name='Pacijenti_a_respons_fede13_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='appointmentattendee',
            unique_together={('appointment', 'korisnik')},
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['updated_at'], name='Pacijenti_c_updated_93f612_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['pacijent'], name='Pacijenti_c_pacijen_248a74_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['doktor'], name='Pacijenti_c_doktor__33e894_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['sestra'], name='Pacijenti_c_sestra__29216b_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['conversation', 'korisnik'], name='Pacijenti_p_convers_fa384a_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['role'], name='Pacijenti_p_role_b0fdb3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('conversation', 'korisnik')},
        ),
        migrations.AddIndex(
            model_name='messagestatus',
            index=models.Index(fields=['participant', 'message'], name='Pacijenti_m_partici_24ee58_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagestatus',
            unique_together={('message', 'participant')},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='Pacijenti_m_convers_8a29ad_idx'),
        ),
    ]
